import { NextRequest, NextResponse } from "next/server";
import { getInstallScript, getInstallTemplate, InstallTemplate } from "@/lib/install-scripts";

const REPO = "marcelocra/devmagic";

/**
 * Generate a small bash installer for a template file group. Everything
 * interpolated here comes from the repo-controlled registry
 * (www/data/install-scripts.yml), never from user input — the only
 * user-controlled bit is the boolean `force` flag.
 */
function generateTemplateInstaller(template: InstallTemplate, ref: string, force: boolean): string {
  const base = `https://raw.githubusercontent.com/${REPO}/${ref}`;

  const installs = template.files.map((f) => `install_file "${f.src}" "${f.dest}"`).join("\n");

  const notes = (template.notes ?? []).map((n) => `echo "💡 ${n.replace(/"/g, '\\"')}"`).join("\n");

  return `#!/bin/bash
# DevMagic template: ${template.name} (${template.id})
# Generated by https://devmagic.run/install/${template.id} — review before running.
# ${template.description}
set -e

BASE="${base}"
FORCE="${force ? "1" : "0"}"
REPO_URL_PLACEHOLDER="https://github.com/YOUR_ORG/YOUR_REPO"

if ! command -v curl >/dev/null 2>&1; then
    echo "❌ curl is not installed. Please install curl to continue."
    exit 1
fi

# Detect this project's repository URL, for templates that link back to it
# (e.g. changelog release links). Falls back to an obvious placeholder.
REPO_URL=""
if command -v git >/dev/null 2>&1; then
    ORIGIN=$(git remote get-url origin 2>/dev/null || true)
    if [ -n "$ORIGIN" ]; then
        # Normalize: git@host:owner/repo(.git) → https://host/owner/repo
        REPO_URL=$(printf '%s' "$ORIGIN" | sed -E 's#^git@([^:]+):#https://\\1/#; s#\\.git$##')
    fi
fi
# Only accept URL-safe characters (the value is used in a sed replacement).
if ! printf '%s' "$REPO_URL" | grep -Eq '^[A-Za-z0-9./:_-]+$'; then
    REPO_URL="$REPO_URL_PLACEHOLDER"
fi

fill_placeholders() {
    local dest="$1"
    if grep -q "{{REPO_URL}}" "$dest" 2>/dev/null; then
        sed -i.bak "s#{{REPO_URL}}#\${REPO_URL}#g" "$dest" && rm -f "$dest.bak"
        if [ "$REPO_URL" = "$REPO_URL_PLACEHOLDER" ]; then
            echo "⚠️  Couldn't detect your git remote — edit the repository URL in $dest"
        fi
    fi
}

install_file() {
    local src="$1" dest="$2"
    if [ -e "$dest" ] && [ "$FORCE" != "1" ]; then
        echo "⚠️  $dest already exists, skipping (add ?force=1 to the URL to overwrite)"
        return 0
    fi
    local dir
    dir=$(dirname "$dest")
    [ "$dir" != "." ] && mkdir -p "$dir"
    curl -fsSL "$BASE/$src" -o "$dest"
    fill_placeholders "$dest"
    echo "✓ $dest"
}

echo "🚀 DevMagic template: ${template.name}"
echo

${installs}

echo
${notes ? `${notes}\necho\n` : ""}echo "✅ Done. Review the files and commit the ones you want to keep."
`;
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ script: string }> }) {
  const { script: scriptId } = await params;

  // Extract version from URL if present (e.g., /install/prettier@v1.0.0)
  let ref = "main";
  let actualScriptId = scriptId;

  const match = scriptId.match(/^(.+)@(.+)$/);
  if (match && match[1] && match[2]) {
    actualScriptId = match[1];
    ref = match[2];
  }

  // Template file groups are generated on the fly from the registry.
  const template = getInstallTemplate(actualScriptId);
  if (template) {
    const force = request.nextUrl.searchParams.get("force") === "1";
    return new NextResponse(generateTemplateInstaller(template, ref, force), {
      status: 200,
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": ref === "main" ? "public, max-age=300" : "public, max-age=31536000",
        "X-DevMagic-Version": ref,
        "X-DevMagic-Template": actualScriptId,
      },
    });
  }

  // Get script metadata
  const scriptMeta = getInstallScript(actualScriptId);
  if (!scriptMeta) {
    return new NextResponse(`Install script not found: ${actualScriptId}`, {
      status: 404,
      headers: {
        "Content-Type": "text/plain",
      },
    });
  }

  // Extract package manager from query params
  const packageManager = request.nextUrl.searchParams.get("pm") || "pnpm";

  // Validate package manager
  const validPackageManagers = ["pnpm", "npm", "yarn", "bun"];
  if (!validPackageManagers.includes(packageManager)) {
    return new NextResponse(
      `Invalid package manager: ${packageManager}. Supported: ${validPackageManagers.join(", ")}`,
      {
        status: 400,
        headers: {
          "Content-Type": "text/plain",
        },
      },
    );
  }

  // Construct the GitHub raw URL
  const scriptUrl = `https://raw.githubusercontent.com/${REPO}/${ref}/${scriptMeta.scriptPath}`;

  try {
    // Fetch the script from GitHub
    const response = await fetch(scriptUrl);

    if (!response.ok) {
      return new NextResponse(`Installation script not found for version: ${ref}\nScript: ${scriptMeta.name}`, {
        status: 404,
        headers: {
          "Content-Type": "text/plain",
        },
      });
    }

    let script = await response.text();

    // If the script supports package managers, inject the PACKAGE_MANAGER variable
    if (scriptMeta.supportsPackageManagers && packageManager !== "pnpm") {
      // Add the package manager as an environment variable at the top of the script
      // Find the first non-shebang, non-comment line
      const lines = script.split("\n");
      let insertIndex = 0;

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (line && !line.startsWith("#")) {
          insertIndex = i;
          break;
        }
        if (i > 0 && !line.startsWith("#")) {
          insertIndex = i;
          break;
        }
      }

      // Insert the environment variable
      lines.splice(insertIndex, 0, `export PACKAGE_MANAGER="${packageManager}"`);
      script = lines.join("\n");
    }

    // Serve the script as plain text
    return new NextResponse(script, {
      status: 200,
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": ref === "main" ? "public, max-age=300" : "public, max-age=31536000",
        "X-DevMagic-Version": ref,
        "X-DevMagic-Script": actualScriptId,
        "X-DevMagic-PackageManager": packageManager,
      },
    });
  } catch (error) {
    return new NextResponse(
      `Error fetching installation script: ${error instanceof Error ? error.message : "Unknown error"}`,
      {
        status: 500,
        headers: {
          "Content-Type": "text/plain",
        },
      },
    );
  }
}
